### ISSUE TITLE
Let the user decide whether to use the "New Tab" page or not

### ISSUE THREAD

**Issue by stefanbuck** [rgehan/octolenses-browser-extension#30]
**Is your feature request related to a problem? Please describe.**
Like many people I really like [Momentum
](https://chrome.google.com/webstore/detail/momentum/laookkfknpbbblfpciffpaejjkokdgca) as my new tab view. Since your extensions is using the same space, I have to decide which one I like / need more. 

Btw. I took me a moment to figure where to find the extension. 

**Describe the solution you'd like**
Move the extensions out of the new tab space and integrate with GitHub.com. A content script allows you do modify the DOM so you an inject a button on GitHub.com which triggers a new view.

**Comment by rgehan** [comment]
While I agree this can conflict with existing extensions, I don't want to make the extension more difficult to access.

I'll however see if I can make the New Tab option opt-in, instead of a default. You could then open OctoLenses by clicking the icon or maybe via a shortcut.

> I took me a moment to figure where to find the extension

You mean the link to the chrome store? If so, I'll make it easier to find thanks!

**Comment by stefanbuck** [comment]
No, the chrome store link is not what I'm talking about. I miss the first sentence which explain that this extension hooks into a new tab 😊 

>Watch your repos and discover awesome things directly **from your New Tab page**
